### ISSUE TITLE
[Bug]: Connecting to the arrow below the node will disappear when it is folded.

### ISSUE THREAD

**Issue by wwjCMP** [Quorafind/Obsidian-Collapse-Node#10]
### Bug Description

Connecting to the arrow below the node will disappear when it is folded.
![Snipaste_2023-11-09_05-59-19](https://github.com/Quorafind/Obsidian-Collapse-Node/assets/32979859/948ce35f-5e29-4f5a-a4da-6125726067f5)
![Snipaste_2023-11-09_05-59-07](https://github.com/Quorafind/Obsidian-Collapse-Node/assets/32979859/cd47c143-8af9-46cf-8af2-db81ff3b7611)

### Obsidian Version

1.4.16

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
You can zoom in to see the arrow.
