### ISSUE TITLE
Feature Request: Readability, Minimalism theme [Ready code inside]

### ISSUE THREAD

**Issue by GothLab** [Quorafind/Obsidian-Collapse-Node#14]
### Feature Requested

![image](https://github.com/Quorafind/Obsidian-Collapse-Node/assets/53623054/f09b0745-aa12-4b99-a724-01f2e57e9e9c)
[collapse-node.zip](https://github.com/Quorafind/Obsidian-Collapse-Node/files/14405405/collapse-node.zip)
Ive added some css changes, and more subtle colors.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Thanks. a settings to enable minimal control header has been added in lastest version
