### ISSUE TITLE
[Bug]: main.js file missing

### ISSUE THREAD

**Issue by TimothyMRead** [Quorafind/Obsidian-Collapse-Node#15]
### Bug Description

According the manual installation notes there has to be a main.js file but I can't find it. Any ideas?

### To Reproduce

Download the zip of code, uncompress, move folder to plugin folder.

### Obsidian Version

1.5.11

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
You can install it from [release](https://github.com/Quorafind/Obsidian-Collapse-Node/releases/latest)
