### ISSUE TITLE
[Bug]: Renaming files won't update live

### ISSUE THREAD

**Issue by Pixel3ro** [Quorafind/Obsidian-Collapse-Node#17]
### Bug Description

when you rename a node/file, it's name on the card will not update immediately. the canvas needs to be close and opened again for it to update. it'd be nice to have it update live. 

### Obsidian Version

1.5.12

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Will be added soon.
