### ISSUE TITLE
[Bug]: Labels aren't collapsed

### ISSUE THREAD

**Issue by irvnriir** [Quorafind/Obsidian-Collapse-Node#19]
### Bug Description

https://github.com/Quorafind/Obsidian-Collapse-Node/assets/13949704/9ad61758-208f-4a43-8cf2-275f1e3771cb

### Obsidian Version

1.5.12.0

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Jeremy-JT-Thompson** [comment]
I would add that there is no reason to create an additional label for a canvas group.  The group is already collapsable.  Adding a collapsable title to the group is redundant.  All that is needed is the ability to select multiple groups and collapse/expand them the same way that is done for several nodes. Thanks!
![image](https://github.com/Quorafind/Obsidian-Collapse-Node/assets/170807427/b8e88bac-c517-48f0-a78d-d17972f6b83a)

**Comment by thehyperadvisor** [comment]
> I would add that there is no reason to create an additional label for a canvas group. The group is already collapsable. Adding a collapsable title to the group is redundant. All that is needed is the ability to select multiple groups and collapse/expand them the same way that is done for several nodes. Thanks! ![image](https://private-user-images.githubusercontent.com/170807427/333801383-b8e88bac-c517-48f0-a78d-d17972f6b83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTE2MTUsIm5iZiI6MTcxODcxMTMxNSwicGF0aCI6Ii8xNzA4MDc0MjcvMzMzODAxMzgzLWI4ZTg4YmFjLWM1MTctNDhmMC1hNzhkLWQxNzk3MmY2YjgzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMTQ4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzNkYjQ4ZmQwODlhYWNkOWVmYjA5ZDVmYjIzYzU1OTEzYjNmNzZiNGMyODIxYzE3NDhiM2RjNjA2NDNlNTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FkmuOPMDZywc9Ttzo6Cf-6rdkuiSOcrSedC0SMmRN4c)

Jeremy, canvas groups are only collapsible if you have a plugin(Advanced Canvas or this plugin) enabled. By default they do not collapse.

**Comment by Jeremy-JT-Thompson** [comment]
Fair enough.  Do you feel it is common for many of the users to have the Advanced Canvas plugin enabled?  Perhaps something to account for this redundancy if it commonly impacts a large percentage of users?  Thanks for the great work!

**Comment by thehyperadvisor** [comment]
Plugins not playing well with others are a common problem with plugins in obsidian. Not sure how to get around that. I like the Advanced Canvas plugin but I've been having issues with it and Obsidian Sync (yet another example of plugins not playing well together) so I've decided to disable the Advanced Canvas plugin. p.s. I'm not a contributor of this project. I'm a user just like you. :)

**Comment by Jeremy-JT-Thompson** [comment]
Thanks, Anotone.  We'll keep our fingers crossed.

**Comment by Quorafind** [comment]
fixed in latest version.
