### ISSUE TITLE
[Bug]: Does not seem to be working anymore Obsidian v1.7.4

### ISSUE THREAD

**Issue by aikruger** [Quorafind/Obsidian-Collapse-Node#25]
### Bug Description

It is unable to load with Obsidian v1.7.4

### Obsidian Version

1.7.4

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by damianjyates** [comment]
I would like to confirm that this plugin is not collapsing cards in canvas.  Is this plugin still being maintained??

**Comment by jaspimeran** [comment]
Not working anymore
Please this was one of the most important feature for the Canvas

**Comment by ONOVAR** [comment]
+1

**Comment by santiyounger** [comment]
It's not working for me either. I would really love to be able to use this plugin again Thanks!

**Comment by Quorafind** [comment]
Fixed.
