### ISSUE TITLE
[Bug]: The newly added object does not display the title

### ISSUE THREAD

**Issue by wwjCMP** [Quorafind/Obsidian-Collapse-Node#9]
### Bug Description

The newly added object does not display the title. The title can only be displayed after this plug-in is re-enabled.

### Obsidian Version

1.4.16

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Or you can refresh the leaf by reopening it.

**Comment by amiraiman** [comment]
> Or you can refresh the leaf by reopening it.

Wont' work if I reopen the node. I have to close the canvas file and reopen again to make it show the title.
